version: "3.8"
networks:
    dbBack:
volumes:
    mysql-volume:
    pip_cache:
services:

    mysql_db:
        image: mysql:5.7
        networks:
            - dbBack
        volumes:
            - type: volume
              source: mysql-volume
              target: /var/lib/mysql
        environment:
          - DJANGO_SETTINGS_MODULE=todobakend.settings.testSettings
          - MYSQL_DATABASE=todobackend
          - MYSQL_ROOT_PASSWORD=password
        expose:
          - "3306"

    django_tester:
        build:
          context: ../../../
          dockerfile: Dockerfiles/todoBuild/DevImg/Dockerfile
        networks:
           - dbBack
        volumes:
           - type: volume
             source: pip_cache
             target: /cache
        depends_on:
            - mysql_db
        environment:
          - MYSQL_DBNAME=todobackend
          - MYSQL_USER=root
          - MYSQL_PASSWORD=password
          - MYSQL_HOST=mysql_db
          - TEST_OUTPUT_DIR=/reports
