FROM node:14.8.0-alpine3.10
LABEL "AUTHOR_NAME"="Karthik Nagadevara"
LABEL "AUTHOR_EMAIL"="vnsk.1991@gmail"
LABEL "VER"="00.00.01"
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm" , "run" , "dev"]