version: '3.8'

networks:
    frontend:
    backend:

volumes:
    mysql-volume:
        
services: 

    proxy-layer:
        image: nginx:stable-alpine
        networks: 
            - frontend
        ports:
            - "80:80"
        volumes:
            - type: volume
              source: ./nginx.conf
              target: /etc/nginx/nginx.conf        

    webServer:
        image: httpd:2.4-alpine
        volumes:
            - type: volume
              source: ./index.html
              target: /usr/local/apache2/htdocs/index.html        
        networks: 
            - frontend
            - backend
            
    db-layer:
        image: mysql:8.0
        environment: 
            - MYSQL_ROOT_PASSWORD=killerJoy718293
        volumes:
            - type: volume
              source: mysql-volume
              target: /var/lib/mysql
        networks: 
            - backend
        ports:
            - "3306:3306"